CREATE SCHEMA TESTE;

CREATE TABLE CLIENTE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(1000),
    SOBRENOME VARCHAR(1000),
    DOCUMENTO VARCHAR(50),
    DT_CADASTRO DATETIME,
    DT_ALTERACAO DATETIME,
    CD_USUARIO_CADASTRADO BIGINT,
    CD_USUARIO_ALTERACAO BIGINT,
    PRIMARY KEY(ID)
);

SELECT * FROM CLIENTE;

DROP TABLE CLIENTE;

INSERT INTO CLIENTE (NOME, SOBRENOME, DOCUMENTO)
VALUES ('ANA', 'CAROLINA','01234567890');